#!/bin/sh

set -e

mkdir -p /opt/tpm-store/share/my-config

####

mkdir -p /root /home /etc/skel

# На DigitalOcean /root/.bashrc такой же, как и у юзеров
for I in /root /home/* /etc/skel; do
	[ -e "$I" ] && my-config-cat "$I/.hushlogin" < /dev/null
	[ -e "$I/.bashrc" ] && my-config-change-lines "$I/.bashrc" "#force_color_prompt=yes" "force_color_prompt=yes"
	rm -f "$I/.bash_logout"
done

####

for I in 1 2 3 4 5 6 7 8 9; do
	my-config-mkdir "/mnt/$I"
done
