#!/bin/sh

set -e

# Сперва restore, а потом delete, а то вдруг мы сперва restore'им какой-нибудь файл, а потом удаляем?

while IFS="" read -r FILE; do
	sed -i 's/^.* #my-config# //' "$FILE"
done < /opt/tpm-store/share/my-config/to-restore

sort -r /opt/tpm-store/share/my-config/to-delete > /opt/tpm-store/share/my-config/to-delete-reversed

while IFS="" read -r FILE; do
	if [ -d "$FILE" ]; then
		rmdir "$FILE" 2> /dev/null || :
		:
	else
		rm -f "$FILE"
	fi
done < /opt/tpm-store/share/my-config/to-delete-reversed

rm -r /opt/tpm-store/share/my-config
